In [9]:
import numpy as np

In [12]:
dim = 10

In [25]:
alpha = 0.95

In [29]:
smallest_coef = 0

In [30]:
largest_coef = 1

In [20]:
chol = -np.eye(dim)

In [21]:
chol

array([[-1., -0., -0., -0., -0., -0., -0., -0., -0., -0.],
       [-0., -1., -0., -0., -0., -0., -0., -0., -0., -0.],
       [-0., -0., -1., -0., -0., -0., -0., -0., -0., -0.],
       [-0., -0., -0., -1., -0., -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -1., -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -1., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -1., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -0., -1., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -0., -0., -0., -0., -0., -1.]])

In [22]:
aux = np.random.rand(dim, dim)

In [23]:
aux

array([[ 0.86202391,  0.23425265,  0.2852024 ,  0.82482391,  0.40284164,
         0.24675772,  0.50234427,  0.31884472,  0.69332294,  0.9656451 ],
       [ 0.17625966,  0.50381558,  0.32961599,  0.64572665,  0.93178755,
         0.77394551,  0.74581826,  0.19055248,  0.3580727 ,  0.04455465],
       [ 0.16923834,  0.12760625,  0.38908888,  0.55133672,  0.51024406,
         0.76692267,  0.65430351,  0.67279413,  0.44339343,  0.83969793],
       [ 0.46774757,  0.59100395,  0.54268102,  0.84436611,  0.99569408,
         0.11666655,  0.24250156,  0.50447623,  0.63855428,  0.97751827],
       [ 0.36512066,  0.54933654,  0.93138115,  0.90927278,  0.81937359,
         0.19581052,  0.46726109,  0.33793414,  0.13930892,  0.04607374],
       [ 0.42693873,  0.98975384,  0.80828602,  0.80047466,  0.74331207,
         0.40771301,  0.36541253,  0.4919562 ,  0.21817496,  0.53984285],
       [ 0.818683  ,  0.0683724 ,  0.91152797,  0.60730888,  0.93817604,
         0.8518504 ,  0.28117071,  0.57610711

In [26]:
aux[aux < alpha] = 0

In [27]:
aux

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.9656451 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.99569408,
         0.        ,  0.        ,  0.        ,  0.        ,  0.97751827],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.98975384,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        

In [31]:
aux[aux > alpha] = (smallest_coef + (largest_coef - smallest_coef) * np.random.rand(np.sum(aux > alpha)))

In [32]:
aux

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.53093753],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.92743293,
         0.        ,  0.        ,  0.        ,  0.        ,  0.11930478],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.5347116 ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        

In [33]:
aux = np.tril(aux, k=-1)

In [34]:
aux

array([[ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.5347116,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.      

In [47]:
permutation = np.random.permutation(dim)

In [48]:
permutation

array([4, 8, 0, 9, 3, 6, 1, 5, 2, 7])

In [51]:
aux = aux[permutation].T[permutation]

In [52]:
aux

array([[ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.5347116,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.      

In [53]:
chol += aux

In [55]:
chol

array([[-1.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       , -1.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       , -1.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       , -1.       ,  0.5347116,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       , -1.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        -1.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       , -1.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.      

In [54]:
prec = np.dot(chol.T, chol)

In [56]:
prec

array([[ 1.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  1.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       , -0.5347116,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       , -0.5347116,  1.2859165,
         0.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         1.       ,  0.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
         0.       ,  1.       ,  0.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.      